### ISSUE TITLE
Exclude words panel option for wordcloud panel

### ISSUE THREAD

**Issue by aFacelessMan** [raulsperoni/magnesium-wordcloud-panel#3]
Following your suggestion of opening an issue in GitHub!

I think it would be beneficial to be able to exclude certain words from the panel within the options tab in Grafana rather than on the Elasticsearch side.

**Comment by raulsperoni** [comment]
Thanks @Almyk for your contribution! Merged and waiting for grafana to accept new version: https://github.com/grafana/grafana-plugin-repository/pull/896
