### ISSUE TITLE
Dashboard issue

### ISSUE THREAD

**Issue by a8478836** [raulsperoni/magnesium-wordcloud-panel#4]
Hello.

Mr. Raulsperoni.

I made a wordcloud on grafana dashboard.

but there is an error.

error is 'e.series[n.series_index] is undefined' like below.

![image](https://user-images.githubusercontent.com/28583606/88514342-dfc74500-d024-11ea-8788-85e34be7f3db.png)

but it is up and running again like below in grafana Edit Panel.

![image](https://user-images.githubusercontent.com/28583606/88514677-77c52e80-d025-11ea-9361-a70b5c5bdb18.png)

**Comment by raulsperoni** [comment]
Hi, could you please check https://github.com/raulsperoni/magnesium-wordcloud-panel/issues/2 ?

**Comment by a8478836** [comment]
Hi. Sorry, that doesn't works in my case.

I don't use Elatricsearch but Influxdb.

then, below is my 'Data' tab.

![image](https://user-images.githubusercontent.com/28583606/88630130-22ebeb80-d0eb-11ea-8ed5-33bb60f5cc70.png)

and this is my query and transform

![image](https://user-images.githubusercontent.com/28583606/88630208-37c87f00-d0eb-11ea-83ba-0c837e71f119.png)

![image](https://user-images.githubusercontent.com/28583606/88630274-4e6ed600-d0eb-11ea-8a87-acdf608ad406.png)

I try to use 'Reduce' option in Transform. but it is same too.

Thank you.

**Comment by raulsperoni** [comment]
Ok, maybe you see letters because it's ordering the result by word value
and not doc count as it should

**Comment by a8478836** [comment]
oops.. Sorry. I can see doc on my screen :/

but, you said 'Ok, maybe you see letters because it's ordering the result by word value'

I got a point, so it woks very well.

There are many fields, but if i can control 'Transform' then it works very well.

I make a wordcloud. Wonderful.

Thanks for your help

you can close this issue. Thank you.

**Comment by raulsperoni** [comment]
great!

**Comment by afonsoc12** [comment]
Hi @raulsperoni and @a8478836 ,

I am having this exact same issue, with the error message 'Cannot read property 'fields' of undefined'

Please take a look at these screenshots
<details><summary></summary>
<p>

![image](https://user-images.githubusercontent.com/20598780/113605162-2a7e6f80-963e-11eb-97f7-7002c8d8a2b4.png)

![image](https://user-images.githubusercontent.com/20598780/113605205-3d913f80-963e-11eb-9fff-0d9352a44c52.png)

![image](https://user-images.githubusercontent.com/20598780/113605527-b1cbe300-963e-11eb-92e4-92d51516b829.png)

![image](https://user-images.githubusercontent.com/20598780/113605878-2acb3a80-963f-11eb-8aa9-85c49f164cd9.png)


</p>
</details>

As you can see, the data is properly formatted, or is there anything I am missing?

Thanks!

**Comment by raulsperoni** [comment]
Hi! I would try changing the Series Index, that seems to be the problem
